version: '3'
services:
  app:
    build: ./application/
    container_name: app
    ports:
      - "8080:80"
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "6000:5432"
    restart: always
    env_file:
      - "./.env"
    environment:
      POSTGRES_PASSWORD: 'password123'
    volumes:
      - ./data:/var/lib/postgresql/data
